version: "2.2"

services:

  redis:
    image: redis:latest
    container_name: redis  
    ports:
      - 6379:6379
    networks:
      - redis-network
    volumes:    
      - redisdata:/data
volumes:
  redisdata:
    driver: local

networks:
  redis-network:
    driver: bridge